---
execute: 
  cache: false
---

# 前言 {.unnumbered}

## Hello and welcome {.unnumbered}

本书所介绍的内容由来已久。[openair]{.pkg} 项目最初由英国国家自然环境研究委员会(NERC)资助，启动至今已十年有余。项目旨在创建一个*开源、易用*的空气质量数据分析工具以弥补在该领域上的明显不足。R语言在当时还远远没有达到目前的流行程度，但是已经展现出蓬勃发展的态势。

本书分为以下几大部分内容，将涵盖空气质量数据分析的方方面面。

-   **数据导入** 主要介绍如何方便的获取英国国家和地方监测网络的空气质量数据以及全球气象数据。

-   **定向类分析** 包含风玫瑰和污染玫瑰、双变量极坐标图、后向轨迹等大量常用功能。

-   **时间序列和趋势类分析** 包含丰富的时间变化分析手段以及灵活的趋势评估方法。

-   **模型评估** 包含泰勒图、常用模型评估指标分析、条件分位数图等功能。

-   **交互式地图** 介绍如何在可交互地图上高效的浏览英国空气质量监测网络数据和绘制定向分析结果；主要用于对污染源的定位。

-   **Utility functions** 介绍多个小工具以满足不同时间尺度上的数据聚合，相关性分析以及在空气污染分析中可能遇到的各种常见需求。

[openair]{.pkg} 当然不可能满足用户的一切分析设想，但是通过灵活的运用现有功能，相信对大部分需求能够具有广泛的适应性。同时，将R语言作为数据分析的平台环境，其本身也会不断赋予用户更多的拓展和创新空间。 

[openair]{.pkg} 开发于前 [ggplot2]{.pkg} 和 ['tidyverse'](https://www.tidyverse.org)时代，使用当时功能最强大的  [lattice]{.pkg} 包来制图。尽管早已时过境迁，但是目前还在一直沿用之前的制图引擎，这主要是考虑到 [openair]{.pkg} 已经在世界范围内 (see downloads [here](https://davidcarslaw.github.io/openair/)) 被广泛使用，而且最初“为院校、机构、公司提供软件工具”的项目目标已经达成————因此我们选择维持现状。

未来我们可能终将切换到[ggplot2]{.pkg}，因为新生态中的大量拓展功能也将让 [openair]{.pkg} 受益。

以网站发布而不是pdf或者Word文档方式撰写本书（或称使用手册）的原因是为了方便各方。对我来说，可以更方便更新书中的内容同时保证所有内容的可复现性。对读者来说，可以更方便的在浏览器中阅读和跳转章节。由于书中包含大量代码，在网页上浏览本书只需要点击每个代码块右上角的拷贝图标就可以将代码复制进本地的R环境。最后，随着信息将越来越多的以可交互的方式呈现，pdf和Word文档的方式会显得力不从心。

To cite [openair]{.pkg} please use:

Carslaw, D. C., and K. Ropkins. 2012. "openair --- An R package for air quality data analysis." *Environmental Modelling & Software* 27--28 (0): 52--61. <https://doi.org/10.1016/j.envsoft.2011.09.008>.

本文档使用R `r getRversion()` 版本和 [openair]{.pkg} `r packageDescription("openair", field = "Version")`版本生成。

```{r}
#| label: bibmake
#| include: false

library(tidyverse)
library(openair)

# automatically create a bib database for R packages
knitr::write_bib(
  c(
    .packages(),
    'knitr',
    'openair',
    'worldmet'
  ),
  'assets/bib/packages.bib'
)
```
